### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-final-amandapalma#1]
Muy buen trabajo @amandapalma!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 330 / 429
- [ ] HTML > ATRIBUTOS: Todos los `img` deben tener el atributo `title`.
- [ ] HTML > ATRIBUTOS: Todos los `img` deben tener el atributo `alt`.
- [ ] HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un `nav`.
- [ ] HTML > HERO: El texto del título del hero debe ser: Anonymous proxy.
- [ ] HTML > HERO: El texto del subtítulo del hero debe ser: In hac habitasse platea dictumst.
- [ ] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips".
- [ ] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips" que sea un `H2 - H6`.
- [ ] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Looking through a window".
- [ ] HTML > MÓDULO LOOKING: Debe haber un párrafo con el texto "Donec accumsan...".
- [ ] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Ut sed metus".
- [ ] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Lorem ipsum dolor sit amet, consecteur.".
- [ ] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Curabitur ac erat".
- [ ] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Mauris mattis urna quis lorem molestie.".
- [ ] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Morbi dictum".
- [ ] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Aliquam in dolor et dolor tincidunt.".

- [ ] CSS > HAMBURGUESA: El menú de la hamburguesa debe tener fondo azul  0271bc.
- [ ] CSS > HERO: El hero debe tener una imagen de fondo centrada horizontal y verticalmente.
- [ ] CSS > FOOTER: Alguno de los elementos del footer en tablet deben estar maquetado con flexbox > `order`.
- [ ] CSS > TRANSICIONES: Debemos usar alguna transición CSS.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja dímelo cuanto antes por favor.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Anonymous** para buscar el hero. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by amandapalma** [comment]
Hola Miguel! 

Gracias por las correcciones. Te planteo dudas que me surgen con las mejoras propuestas, ¿vale?

_**HTML**_

**1. HTML > ATRIBUTOS: Todos los img deben tener el atributo title.**

Tenía entendido, según mencionó María en varias ocasiones, que en imágenes, el atributo 'title' no es recomendable si ya tienes un atributo 'alt', porque se redunda en la información aportada y puede producir errores. 
Entonces, ¿no sería correcto no usar ese atributo 'title', puesto que ya tengo los 'alt'?


**2. HTML > ATRIBUTOS: Todos los img deben tener el atributo alt.**

Si chequeas las líneas donde aparecen las etiquetas <img> se puede comprobar que todas poseen el atributo 'alt'.
(src>html>partials>header>línea 9)
(src>html>partials>main>línea 14)
(src>html>partials>footer>línea 4)


**3. HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un nav.**

Aunque en el diseño de referencia, en ninguno de los formatos aparezca un menú con opciones, sólo el icono de la hamburguesa ¿siempre debo utilizar <nav> cuando tengo ese icono?


**7. HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips" que sea un H2 - H6.**

¿Por qué debería ser un h2-h6 y no podría ser un p? ¿Cómo sé, en función de el diseño de referencia, que carga semántica tiene ese elemento?

**PUNTOS 4, 6 y 8**
- HERO: El texto del título del hero debe ser: Anonymous proxy.
- MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips”.
- MÓDULO LOOKING: Debe haber un elemento con el texto "Looking through a window”.

Los tres textos existen: 
Anonymous proxy: HTML (src>html>partials>main>línea 14) Y CSS ( scss>components>typography)
Insomnia tips: HTML (partial main.html> línea 20) Y CSS (scss>componets>typography>línea 93)
Looking through a window: HTML (html>partials> main.html> Línea 21) Y CSS (scss/components/_typograhy> línea 36)

Y se les ha aplicado text-transform: uppercase para convertir a mayúscula el primer caracter, como se indicaba en las correcciones del ejercicio de la evaluación intermedia. Entonces, ¿Qué es lo que tendría que corregir aquí?


**PUNTOS 5, 9, 10, 11, 12, 13, 14, 15**

Según las mejoras los textos deben ser exactamente iguales que los del diseño, aunque sean borradores, ya que son muestras de lorem ipsum. 
¿Esto realmente es necesario? Fui obteniendo los textos con el generador de ipsum de code, por eso no son idénticos, pero pensé que eran textos de ejemplo, y por eso los generé así, no como en  de otros textos que sí que son específicos  y sí los escribí exactamente igual.  


_**CSS**_

**1. CSS > HAMBURGUESA: El menú de la hamburguesa debe tener fondo azul 0271bc.**

El color aplicado es el que especificaba el diseño. Lo recogí en la variable $color-primary-medium: #0271bc; 
(scss>core>variables> línea 7)


**2. CSS > HERO: El hero debe tener una imagen de fondo centrada horizontal y verticalmente.**

Estos son los estilos que apliqué:
.hero {
  background-image: url("../images/cover.jpg");
  background-repeat: no-repeat;
  background-size: cover;
}
¿bastaría con añadir un background-position: center; , no?

**3. CSS > FOOTER: Alguno de los elementos del footer en tablet deben estar maquetado con flexbox > order.**

El copy del footer está maqueado con flexbox y contiene la propiedad order.
flexbox: (scss>layout>footer> líneas 30-31)
order: (scss>layout>footer> líneas 54-56) 


**4.  CSS > TRANSICIONES: Debemos usar alguna transición CSS.**

Nada, aquí se me fue totalmente la cabeza pensando que ya las había creado para los botones de de las secciones ‘looking’ y ‘reasons’, y me puse a hacer animaciones como loca. Pero no, sólo incluí estilos para :hover y :active en los botones pero no incluí la propiedad transition para el background-color del hover, como era mi intención.  :( 


Y por último, respecto al código, los ficheros, carpetas y commits diría que están todos en inglés. 


Gracias, y disculpa la parrafada!
